### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by PublicByte** [seamless-foundation/d-noise#1]
# Phases
## Phase 1
- [x] Update system requirements in README.md
- [ ] Remove/rewrite download function
- [ ] Compile Declan Russell's NVidia AI Denoiser command line tool
- [ ] Remove Windows support (the original repository supports windows, but not linux)

## Phase 2
- [ ] Do it yourself! Start from scratch!
- [ ] Add MIT license instead of GPLv3

**Comment by PublicByte** [comment]
I'm not looking forward to contributing anything to the original repository due to its inactivity.
